trigger:
  branches:
    include:
      - main
      - refs/tags/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Python310Build
        timeoutInMinutes: 120
        container: python:3.10.11
        steps:
          - script: python -m venv $(Build.SourcesDirectory)/.venv
            displayName: "Creating virtual environment"
          - task: PipAuthenticate@1
            inputs:
              artifactFeeds: 'bitbloom-artifacts'
              onlyAddExtraIndex: True
          - script: |
              source $(Build.SourcesDirectory)/.venv/bin/activate
              pip install .[test,build]
            displayName: "Installing pvlib"
          - script: |
              source $(Build.SourcesDirectory)/.venv/bin/activate
              python -m pytest tests
            displayName: "Running tests with pytest"
          - task: TwineAuthenticate@1
            inputs:
              artifactFeed: "bitbloom-artifacts"
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
          - script: |
              source $(Build.SourcesDirectory)/.venv/bin/activate
              python setup.py sdist
              python -m twine upload -r "bitbloom-artifacts" --config-file $(PYPIRC_PATH) dist/*.tar.gz
            displayName: "Building and publishing sdist package"
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
